// SPDX-FileCopyrightText: 2024 Demerzel Solutions Limited
// SPDX-License-Identifier: MIT

// Renders Bls.G1.cs and Bls.G2.cs from PointGroup.template. The G1 and G2 bindings are
// identical up to naming, sizes and a handful of explicitly conditional blocks; generating
// both from one template keeps them from drifting apart.

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

string genDir = Path.Combine(FindRepoRoot(), "src", "Nethermind.Crypto.Bls.Gen");
string outDir = Path.Combine(FindRepoRoot(), "src", "Nethermind.Crypto.Bls");
string[] template = File.ReadAllLines(Path.Combine(genDir, "PointGroup.template"));

var groups = new[]
{
    new Group("g1", "Bls.G1.cs", new Dictionary<string, string>
    {
        ["{{P}}"] = "P1",
        ["{{p}}"] = "p1",
        ["{{G}}"] = "g1",
        ["{{OTHER_G}}"] = "g2",
        ["{{GG}}"] = "G1",
        ["{{COMPRESSED_BYTES}}"] = "48",
        ["{{SERIALIZED_BYTES}}"] = "96",
        ["{{NUM_COORDS}}"] = "two",
    }),
    new Group("g2", "Bls.G2.cs", new Dictionary<string, string>
    {
        ["{{P}}"] = "P2",
        ["{{p}}"] = "p2",
        ["{{G}}"] = "g2",
        ["{{OTHER_G}}"] = "g1",
        ["{{GG}}"] = "G2",
        ["{{COMPRESSED_BYTES}}"] = "96",
        ["{{SERIALIZED_BYTES}}"] = "192",
        ["{{NUM_COORDS}}"] = "four",
    }),
};

foreach (Group group in groups)
{
    string path = Path.Combine(outDir, group.FileName);
    File.WriteAllText(path, Render(template, group));
    Console.WriteLine($"generated {path}");
}

static string Render(string[] template, Group group)
{
    StringBuilder output = new();
    output.AppendLine("// <auto-generated>");
    output.AppendLine("// Generated from src/Nethermind.Crypto.Bls.Gen/PointGroup.template. Do not edit directly;");
    output.AppendLine("// edit the template and run: dotnet run --project src/Nethermind.Crypto.Bls.Gen");
    output.AppendLine("// </auto-generated>");
    output.AppendLine("#nullable enable");
    output.AppendLine();

    string? skippedGroup = null;
    foreach (string line in template)
    {
        string trimmed = line.Trim();
        if (trimmed.StartsWith("//<<", StringComparison.Ordinal) && trimmed.EndsWith("-only", StringComparison.Ordinal))
        {
            string conditionGroup = trimmed["//<<".Length..^"-only".Length];
            skippedGroup = conditionGroup == group.Name ? null : conditionGroup;
            continue;
        }
        if (trimmed.EndsWith("-only>>", StringComparison.Ordinal) && trimmed.StartsWith("//", StringComparison.Ordinal))
        {
            skippedGroup = null;
            continue;
        }
        if (skippedGroup is not null)
        {
            continue;
        }

        string rendered = line;
        foreach ((string token, string value) in group.Tokens)
        {
            rendered = rendered.Replace(token, value);
        }
        if (rendered.Contains("{{", StringComparison.Ordinal))
        {
            throw new InvalidOperationException($"Unsubstituted token in line: {rendered}");
        }
        output.AppendLine(rendered);
    }

    if (skippedGroup is not null)
    {
        throw new InvalidOperationException("Unterminated conditional block in template.");
    }

    return output.ToString();
}

static string FindRepoRoot()
{
    string? dir = AppContext.BaseDirectory;
    while (dir is not null && !Directory.Exists(Path.Combine(dir, "src", "Nethermind.Crypto.Bls")))
    {
        dir = Path.GetDirectoryName(dir);
    }
    return dir ?? throw new InvalidOperationException("Repository root not found.");
}

internal sealed record Group(string Name, string FileName, Dictionary<string, string> Tokens);
