// SPDX-FileCopyrightText: 2024 Demerzel Solutions Limited
// SPDX-License-Identifier: MIT

// Modification of original file generated by: https://github.com/supranational/blst/blob/master/bindings/c%23/run.me
// Copyright Supranational LLC
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

using System;
using System.Buffers;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using size_t = nuint;

namespace Nethermind.Crypto;

public static partial class Bls
{
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial ERROR blst_pairing_aggregate_pk_in_g1(Span<long> fp12,
                                    ReadOnlySpan<long> pk, ReadOnlySpan<long> sig,
                                    ReadOnlySpan<byte> msg, size_t msg_len,
                                    ReadOnlySpan<byte> aug, size_t aug_len);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial ERROR blst_pairing_mul_n_aggregate_pk_in_g1(Span<long> fp12,
                                    ReadOnlySpan<long> pk, ReadOnlySpan<long> sig,
                                    ReadOnlySpan<byte> scalar, size_t nbits,
                                    ReadOnlySpan<byte> msg, size_t msg_len,
                                    ReadOnlySpan<byte> aug, size_t aug_len);

    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial ERROR blst_pairing_aggregate_pk_in_g2(Span<long> fp12,
                                    ReadOnlySpan<long> pk, ReadOnlySpan<long> sig,
                                    ReadOnlySpan<byte> msg, size_t msg_len,
                                    ReadOnlySpan<byte> aug, size_t aug_len);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial ERROR blst_pairing_mul_n_aggregate_pk_in_g2(Span<long> fp12,
                                    ReadOnlySpan<long> pk, ReadOnlySpan<long> sig,
                                    ReadOnlySpan<byte> scalar, size_t nbits,
                                    ReadOnlySpan<byte> msg, size_t msg_len,
                                    ReadOnlySpan<byte> aug, size_t aug_len);

    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial size_t blst_pairing_sizeof();
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_pairing_init(Span<long> ctx, [MarshalAs(UnmanagedType.Bool)] bool hash_or_encode,
                                                 ref long dst, size_t dst_len);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_pairing_commit(Span<long> ctx);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial ERROR blst_pairing_merge(Span<long> ctx, ReadOnlySpan<long> ctx1);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool blst_pairing_finalverify(ReadOnlySpan<long> ctx, ReadOnlySpan<long> sig);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_pairing_raw_aggregate(Span<long> ctx, ReadOnlySpan<long> q,
                                                          ReadOnlySpan<long> p);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial nint blst_pairing_as_fp12(ReadOnlySpan<long> ctx);

    public readonly ref struct Pairing
    {
        public readonly ReadOnlySpan<long> Ctx { get => _ctx; }
        public static int Sz { get => _sz; }
        private readonly Span<long> _ctx;
        private static readonly int _sz = (int)blst_pairing_sizeof() / sizeof(long);

        // without this, new Pairing() would skip the constructor below and produce an instance
        // backed by a null buffer, crashing the process on first use
        public Pairing() : this(false)
        { }

        public Pairing(bool hashOrEncode = false, scoped ReadOnlySpan<byte> DST = default)
        {
            int dst_len = DST.Length;
            int add_len = dst_len != 0 ? (dst_len + sizeof(long) - 1) / sizeof(long) : 1;

            Span<byte> dst = new byte[add_len * sizeof(long)];
            DST.CopyTo(dst);

            // The DST is stored in the tail of the context array, immediately after the context
            // struct. blst detects a DST placed at ctx + sizeof(ctx) and re-derives its address
            // from the context pointer on every use, so this stays valid even if the GC moves
            // the array between calls.
            _ctx = new long[Sz + add_len];

            for (int i = 0; i < add_len; i++)
            {
                _ctx[Sz + i] = BitConverter.ToInt64(dst[(i * sizeof(long))..]);
            }

            blst_pairing_init(_ctx, hashOrEncode, ref _ctx[Sz], (size_t)dst_len);
        }

        public readonly ERROR Aggregate(P1Affine pk, P2Affine sig,
                                              ReadOnlySpan<byte> msg, ReadOnlySpan<byte> aug = default)
        {
            return blst_pairing_aggregate_pk_in_g1(_ctx, pk.Point,
                                    sig.Point,
                                    msg, (size_t)msg.Length,
                                    aug, (size_t)(!aug.IsEmpty ? aug.Length : 0));
        }
        public readonly ERROR Aggregate(P2Affine pk, P1Affine sig,
                                             ReadOnlySpan<byte> msg, ReadOnlySpan<byte> aug = default)
        {
            return blst_pairing_aggregate_pk_in_g2(_ctx, pk.Point,
                                    sig.Point,
                                    msg, (size_t)msg.Length,
                                    aug, (size_t)(!aug.IsEmpty ? aug.Length : 0));
        }
        public readonly ERROR MulNAggregate(P2Affine pk, P1Affine sig,
                                                   ReadOnlySpan<byte> scalar, int nbits,
                                                   ReadOnlySpan<byte> msg, ReadOnlySpan<byte> aug = default)
        {
            return blst_pairing_mul_n_aggregate_pk_in_g2(_ctx, pk.Point, sig.Point,
                                    scalar, (size_t)nbits,
                                    msg, (size_t)msg.Length,
                                    aug, (size_t)(!aug.IsEmpty ? aug.Length : 0));
        }
        public readonly ERROR MulNAggregate(P1Affine pk, P2Affine sig,
                                                   ReadOnlySpan<byte> scalar, int nbits,
                                                   ReadOnlySpan<byte> msg, ReadOnlySpan<byte> aug = default)
        {
            return blst_pairing_mul_n_aggregate_pk_in_g1(_ctx, pk.Point, sig.Point,
                                    scalar, (size_t)nbits,
                                    msg, (size_t)msg.Length,
                                    aug, (size_t)(!aug.IsEmpty ? aug.Length : 0));
        }

        public readonly void Commit() { blst_pairing_commit(_ctx); }
        public readonly void Merge(in Pairing a)
        {
            ERROR err = blst_pairing_merge(_ctx, a._ctx);
            if (err != ERROR.SUCCESS)
            {
                throw new BlsException(err);
            }
        }
        public readonly bool FinalVerify(PT sig)
        { return blst_pairing_finalverify(_ctx, sig.Fp12); }

        /// <summary>
        /// Verifies against the signatures accumulated via the <c>sig</c> arguments of
        /// <see cref="Aggregate(P1Affine, P2Affine, ReadOnlySpan{byte}, ReadOnlySpan{byte})"/> calls.
        /// </summary>
        public readonly bool FinalVerify()
        { return blst_pairing_finalverify(_ctx, default); }

        public readonly void RawAggregate(P2Affine q, P1Affine p)
        { blst_pairing_raw_aggregate(_ctx, q.Point, p.Point); }
        public void RawAggregate(P1Affine p, P2Affine q)
        { RawAggregate(q, p); }
        public readonly void RawAggregate(P2 q, P1 p)
        {
            blst_pairing_raw_aggregate(_ctx, new P2Affine(q).Point,
                                            new P1Affine(p).Point);
        }
        public void RawAggregate(P1 p, P2 q)
            => RawAggregate(q, p);
        public readonly unsafe PT AsFp12()
        {
            long[] res = new long[PT.Sz];
            // keep the context pinned while copying: blst_pairing_as_fp12 returns a pointer
            // into the context, which would be left dangling if the GC moved the array
            fixed (long* ctx = _ctx)
            {
                new ReadOnlySpan<long>((void*)blst_pairing_as_fp12(_ctx), PT.Sz).CopyTo(res);
            }
            return new(res);
        }
    }
}
