// SPDX-FileCopyrightText: 2026 Demerzel Solutions Limited
// SPDX-License-Identifier: MIT

// Modification of original file generated by: https://github.com/supranational/blst/blob/master/bindings/c%23/run.me
// Copyright Supranational LLC
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

using System;
using System.Buffers;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using size_t = nuint;

namespace Nethermind.Crypto;

public static partial class Bls
{
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_aggregated_in_g1(Span<long> fp12, ReadOnlySpan<long> p);

    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_aggregated_in_g2(Span<long> fp12, ReadOnlySpan<long> p);

    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial size_t blst_fp12_sizeof();
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_miller_loop(Span<long> fp12, ReadOnlySpan<long> q,
                                                           ReadOnlySpan<long> p);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool blst_fp12_is_one(ReadOnlySpan<long> fp12);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool blst_fp12_is_equal(ReadOnlySpan<long> a, ReadOnlySpan<long> b);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_fp12_sqr(Span<long> ret, ReadOnlySpan<long> a);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_fp12_mul(Span<long> ret, ReadOnlySpan<long> a,
                                                       ReadOnlySpan<long> b);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_final_exp(Span<long> ret, ReadOnlySpan<long> a);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool blst_fp12_finalverify(ReadOnlySpan<long> a, ReadOnlySpan<long> b);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial nint blst_fp12_one();
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool blst_fp12_in_group(ReadOnlySpan<long> a);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_bendian_from_fp12(Span<byte> ret, ReadOnlySpan<long> a);

    // void blst_miller_loop_lines(blst_fp12 *ret, const blst_fp6 Qlines[68],
    //                                         const blst_p1_affine *P);

    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_miller_loop_lines(Span<long> ret, ReadOnlySpan<long> qlines, ReadOnlySpan<long> p);

    // void blst_miller_loop_n(blst_fp12 *ret, const blst_p2_affine *const Qs[],
    //                                         const blst_p1_affine *const Ps[], size_t n);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static unsafe partial void blst_miller_loop_n(Span<long> ret, long** Qs, long** Ps, size_t n);

    public readonly ref struct PT
    {
        public readonly ReadOnlySpan<long> Fp12 { get => _fp12; }
        public static int Sz { get => _sz; }
        private readonly Span<long> _fp12;
        private static readonly int _sz = (int)blst_fp12_sizeof() / sizeof(long);

        public PT(PT orig)
        {
            _fp12 = new long[Sz];
            orig._fp12.CopyTo(_fp12);
        }

        public PT(Span<long> p)
        {
            if (p.Length < Sz)
            {
                throw new ArgumentException($"Invalid point length. Expected {_sz} longs.");
            }
            _fp12 = p[..Sz];
        }

        public PT()
        {
            _fp12 = new long[Sz];
        }

        public PT(P1Affine p) : this()
        { blst_aggregated_in_g1(_fp12, p.Point); }
        public PT(P1 p) : this()
        { blst_aggregated_in_g1(_fp12, new P1Affine(p).Point); }
        public PT(P2Affine q) : this()
        { blst_aggregated_in_g2(_fp12, q.Point); }
        public PT(P2 q) : this()
        { blst_aggregated_in_g2(_fp12, new P2Affine(q).Point); }
        public PT(P2Affine q, P1Affine p) : this()
            => MillerLoop(q, p);
        public PT(P1Affine p, P2Affine q) : this(q, p) { }
        public PT(P2 q, P1 p) : this()
            => MillerLoop(q, p);
        public PT(P1 p, P2 q) : this(q, p) { }

        public void MillerLoop(P2Affine q, P1Affine p)
        { blst_miller_loop(_fp12, q.Point, p.Point); }
        public void MillerLoop(P2 q, P1 p)
            => MillerLoop(q.ToAffine(), p.ToAffine());
        public readonly PT Dup() => new(this);
        public readonly bool IsOne()
            => blst_fp12_is_one(_fp12);
        public readonly bool IsEqual(PT p)
            => blst_fp12_is_equal(_fp12, p._fp12);
        public readonly PT Sqr() { blst_fp12_sqr(_fp12, _fp12); return this; }
        public readonly PT Mul(PT p) { blst_fp12_mul(_fp12, _fp12, p._fp12); return this; }
        public readonly PT FinalExp() { blst_final_exp(_fp12, _fp12); return this; }
        public readonly bool InGroup()
            => blst_fp12_in_group(_fp12);
        public readonly byte[] ToBendian()
        {
            byte[] ret = new byte[12 * P1_COMPRESSED_SZ];
            blst_bendian_from_fp12(ret, _fp12);
            return ret;
        }

        public static bool FinalVerify(PT gt1, PT gt2)
        { return blst_fp12_finalverify(gt1._fp12, gt2._fp12); }

        public static PT One()
        {
            long[] res = new long[Sz];
            return One(res);
        }

        public static unsafe PT One(Span<long> p)
        {
            PT res = new(p);
            new ReadOnlySpan<long>((void*)blst_fp12_one(), Sz).CopyTo(res._fp12);
            return res;
        }

        public void MillerLoopLines(ReadOnlySpan<long> qlines, P1Affine p)
        { blst_miller_loop_lines(_fp12, qlines, p.Point); }

        /// <summary>
        /// Computes the product of <paramref name="npairs"/> Miller loops in one batched pass,
        /// sharing the Fp12 squarings across pairs (faster than multiplying separate
        /// <see cref="MillerLoop(P2Affine, P1Affine)"/> results). The affine points are stored
        /// contiguously in <paramref name="qAffines"/>/<paramref name="pAffines"/>; pairs with a
        /// point at infinity must be filtered out by the caller.
        /// </summary>
        public readonly unsafe PT MillerLoopN(scoped ReadOnlySpan<long> qAffines, scoped ReadOnlySpan<long> pAffines, int npairs)
        {
            ArgumentOutOfRangeException.ThrowIfNegative(npairs);
            if (qAffines.Length < (long)npairs * P2Affine.Sz)
            {
                throw new ArgumentException($"Insufficient points for the given count. Expected {(long)npairs * P2Affine.Sz} longs.", nameof(qAffines));
            }
            if (pAffines.Length < (long)npairs * P1Affine.Sz)
            {
                throw new ArgumentException($"Insufficient points for the given count. Expected {(long)npairs * P1Affine.Sz} longs.", nameof(pAffines));
            }

            // the empty product is one, which blst does not write
            if (npairs == 0)
            {
                One(_fp12);
                return this;
            }

            // [ptr, null] tells blst to read npairs from one contiguous buffer
            fixed (long* q = qAffines)
            fixed (long* p = pAffines)
            {
                long** qs = stackalloc long*[2] { q, null };
                long** ps = stackalloc long*[2] { p, null };
                blst_miller_loop_n(_fp12, qs, ps, (size_t)npairs);
            }
            return this;
        }
    }
}
