// SPDX-FileCopyrightText: 2024 Demerzel Solutions Limited
// SPDX-License-Identifier: MIT

// Modification of original file generated by: https://github.com/supranational/blst/blob/master/bindings/c%23/run.me
// Copyright Supranational LLC
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

using System;
using System.Buffers;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using size_t = nuint;

namespace Nethermind.Crypto;

public static partial class Bls
{
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_keygen(Span<byte> key, ReadOnlySpan<byte> IKM, size_t IKM_len,
                                       ReadOnlySpan<byte> info, size_t info_len);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_keygen_v3(Span<byte> key, ReadOnlySpan<byte> IKM, size_t IKM_len,
                                          ReadOnlySpan<byte> info, size_t info_len);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_keygen_v4_5(Span<byte> key, ReadOnlySpan<byte> IKM, size_t IKM_len,
                                            ReadOnlySpan<byte> salt, size_t salt_len,
                                            ReadOnlySpan<byte> info, size_t info_len);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_keygen_v5(Span<byte> key, ReadOnlySpan<byte> IKM, size_t IKM_len,
                                          ReadOnlySpan<byte> salt, size_t salt_len,
                                          ReadOnlySpan<byte> info, size_t info_len);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_derive_master_eip2333(Span<byte> key,
                                                  ReadOnlySpan<byte> IKM, size_t IKM_len);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_derive_child_eip2333(Span<byte> key,
                                                 ReadOnlySpan<byte> master, uint child_index);

    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_scalar_from_bendian(Span<byte> ret, ReadOnlySpan<byte> key);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_bendian_from_scalar(Span<byte> ret, ReadOnlySpan<byte> key);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool blst_sk_check(ReadOnlySpan<byte> key);

    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_scalar_from_lendian(Span<byte> key, ReadOnlySpan<byte> inp);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_lendian_from_scalar(Span<byte> key, ReadOnlySpan<byte> inp);

    public readonly ref struct SecretKey
    {
        public readonly ReadOnlySpan<byte> Key { get => _key; }
        private readonly Span<byte> _key;

        /// <summary>
        /// Wraps caller-provided storage as the key without copying or validation. The bytes are
        /// interpreted in blst's internal little-endian scalar form; to parse an encoded key use
        /// <see cref="SecretKey(ReadOnlySpan{byte}, ByteOrder)"/>.
        /// </summary>
        [OverloadResolutionPriority(1)]
        public SecretKey(Span<byte> key)
        {
            if (key.Length < 32)
            {
                throw new ArgumentException("Invalid key length. Expected 32 bytes.");
            }
            _key = key[..32];
        }

        public SecretKey() : this(new byte[32])
        { }

        public SecretKey(scoped ReadOnlySpan<byte> IKM, string info) : this()
            => Keygen(IKM, info);
        public SecretKey(scoped ReadOnlySpan<byte> inp, ByteOrder order = ByteOrder.BigEndian) : this()
        {
            switch (order)
            {
                case ByteOrder.BigEndian: FromBendian(inp); break;
                case ByteOrder.LittleEndian: FromLendian(inp); break;
            }
        }

        public readonly void Keygen(scoped ReadOnlySpan<byte> IKM, string info = "")
        {
            ValidateIkm(IKM);
            ReadOnlySpan<byte> info_bytes = Encoding.UTF8.GetBytes(info);
            blst_keygen(_key, IKM, (size_t)IKM.Length,
                             info_bytes, (size_t)info_bytes.Length);
        }
        public readonly void KeygenV3(scoped ReadOnlySpan<byte> IKM, string info = "")
        {
            ValidateIkm(IKM);
            ReadOnlySpan<byte> info_bytes = Encoding.UTF8.GetBytes(info);
            blst_keygen_v3(_key, IKM, (size_t)IKM.Length,
                                info_bytes, (size_t)info_bytes.Length);
        }
        public readonly void KeygenV45(scoped ReadOnlySpan<byte> IKM, string salt, string info = "")
        {
            ValidateIkm(IKM);
            ReadOnlySpan<byte> salt_bytes = Encoding.UTF8.GetBytes(salt);
            ReadOnlySpan<byte> info_bytes = Encoding.UTF8.GetBytes(info);
            blst_keygen_v4_5(_key, IKM, (size_t)IKM.Length,
                                  salt_bytes, (size_t)salt_bytes.Length,
                                  info_bytes, (size_t)info_bytes.Length);
        }
        public readonly void KeygenV5(scoped ReadOnlySpan<byte> IKM, scoped ReadOnlySpan<byte> salt, string info = "")
        {
            ValidateIkm(IKM);
            ReadOnlySpan<byte> info_bytes = Encoding.UTF8.GetBytes(info);
            blst_keygen_v5(_key, IKM, (size_t)IKM.Length,
                                salt, (size_t)salt.Length,
                                info_bytes, (size_t)info_bytes.Length);
        }

        // blst silently returns an all-zero key when given less than 32 bytes of key material
        private static void ValidateIkm(ReadOnlySpan<byte> IKM)
        {
            if (IKM.Length < 32)
            {
                throw new ArgumentException("Insufficient key material. Expected at least 32 bytes.", nameof(IKM));
            }
        }
        public readonly void KeygenV5(scoped ReadOnlySpan<byte> IKM, string salt, string info = "")
            => KeygenV5(IKM, Encoding.UTF8.GetBytes(salt), info);
        public readonly void DeriveMasterEip2333(scoped ReadOnlySpan<byte> IKM)
        {
            ValidateIkm(IKM);
            blst_derive_master_eip2333(_key, IKM, (size_t)IKM.Length);
        }
        public SecretKey(SecretKey master, uint childIndex)
        {
            _key = new byte[32];
            blst_derive_child_eip2333(_key, master.Key, childIndex);
        }

        public readonly void FromBendian(scoped ReadOnlySpan<byte> inp)
        {
            if (inp.Length != 32)
            {
                throw new BlsException(ERROR.BADENCODING);
            }

            blst_scalar_from_bendian(_key, inp);

            if (!blst_sk_check(_key))
            {
                throw new BlsException(ERROR.BADENCODING);
            }
        }
        public readonly void FromLendian(scoped ReadOnlySpan<byte> inp)
        {
            if (inp.Length != 32)
            {
                throw new BlsException(ERROR.BADENCODING);
            }

            blst_scalar_from_lendian(_key, inp);

            if (!blst_sk_check(_key))
            {
                throw new BlsException(ERROR.BADENCODING);
            }
        }

        public readonly byte[] ToBendian()
        {
            byte[] ret = new byte[32];
            blst_bendian_from_scalar(ret, _key);
            return ret;
        }
        public readonly byte[] ToLendian()
        {
            byte[] ret = new byte[32];
            blst_lendian_from_scalar(ret, _key);
            return ret;
        }
    }
}
