// SPDX-FileCopyrightText: 2026 Demerzel Solutions Limited
// SPDX-License-Identifier: MIT

// Modification of original file generated by: https://github.com/supranational/blst/blob/master/bindings/c%23/run.me
// Copyright Supranational LLC
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

using System;
using System.Buffers;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using size_t = nuint;

namespace Nethermind.Crypto;

public static partial class Bls
{
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_scalar_from_be_bytes(Span<byte> ret, ReadOnlySpan<byte> inp,
                                                                   size_t inp_len);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_scalar_from_le_bytes(Span<byte> ret, ReadOnlySpan<byte> inp,
                                                                   size_t inp_len);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool blst_sk_add_n_check(Span<byte> ret, ReadOnlySpan<byte> a,
                                                             ReadOnlySpan<byte> b);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool blst_sk_sub_n_check(Span<byte> ret, ReadOnlySpan<byte> a,
                                                             ReadOnlySpan<byte> b);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool blst_sk_mul_n_check(Span<byte> ret, ReadOnlySpan<byte> a,
                                                             ReadOnlySpan<byte> b);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_sk_inverse(Span<byte> ret, ReadOnlySpan<byte> a);

    public readonly ref struct Scalar
    {
        public readonly ReadOnlySpan<byte> Val { get => _val; }
        private readonly Span<byte> _val;

        /// <summary>
        /// Wraps caller-provided storage as the scalar without copying or validation. The bytes are
        /// interpreted in blst's internal little-endian form; to parse an encoded value use
        /// <see cref="Scalar(ReadOnlySpan{byte}, ByteOrder)"/>.
        /// </summary>
        [OverloadResolutionPriority(1)]
        public Scalar(Span<byte> val)
        {
            if (val.Length < 32)
            {
                throw new ArgumentException("Invalid scalar length. Expected 32 bytes.");
            }
            _val = val[..32];
        }

        public Scalar() : this(new byte[32])
        { }

        public Scalar(ReadOnlySpan<byte> inp, ByteOrder order = ByteOrder.BigEndian) : this()
        {
            switch (order)
            {
                case ByteOrder.BigEndian: FromBendian(inp); break;
                case ByteOrder.LittleEndian: FromLendian(inp); break;
            }
        }
        private Scalar(Scalar orig) : this() { orig._val.CopyTo(_val); }

        public readonly Scalar Dup() => new(this);

        public readonly void FromBendian(ReadOnlySpan<byte> inp)
        {
            blst_scalar_from_be_bytes(_val, inp, (size_t)inp.Length);
        }
        public readonly void FromLendian(ReadOnlySpan<byte> inp)
        {
            blst_scalar_from_le_bytes(_val, inp, (size_t)inp.Length);
        }

        public readonly byte[] ToBendian()
        {
            byte[] ret = new byte[32];
            blst_bendian_from_scalar(ret, _val);
            return ret;
        }
        public readonly byte[] ToLendian()
        {
            byte[] ret = new byte[32];
            blst_lendian_from_scalar(ret, _val);
            return ret;
        }

        public readonly Scalar Add(SecretKey a)
        {
            if (!blst_sk_add_n_check(_val, _val, a.Key))
            {
                throw new BlsException(ERROR.BADSCALAR);
            }
            return this;
        }
        public readonly Scalar Add(Scalar a)
        {
            if (!blst_sk_add_n_check(_val, _val, a._val))
            {
                throw new BlsException(ERROR.BADSCALAR);
            }
            return this;
        }
        public readonly Scalar Sub(Scalar a)
        {
            if (!blst_sk_sub_n_check(_val, _val, a._val))
            {
                throw new BlsException(ERROR.BADSCALAR);
            }
            return this;
        }
        public readonly Scalar Mul(Scalar a)
        {
            if (!blst_sk_mul_n_check(_val, _val, a._val))
            {
                throw new BlsException(ERROR.BADSCALAR);
            }
            return this;
        }
        public readonly Scalar Inverse()
        { blst_sk_inverse(_val, _val); return this; }

        public static Scalar operator +(Scalar a, Scalar b)
            => a.Dup().Add(b);
        public static Scalar operator -(Scalar a, Scalar b)
            => a.Dup().Sub(b);
        public static Scalar operator *(Scalar a, Scalar b)
            => a.Dup().Mul(b);
        public static Scalar operator /(Scalar a, Scalar b)
            => b.Dup().Inverse().Mul(a);
    }
}
