// SPDX-FileCopyrightText: 2024 Demerzel Solutions Limited
// SPDX-License-Identifier: MIT

// Modification of original file generated by: https://github.com/supranational/blst/blob/master/bindings/c%23/run.me
// Copyright Supranational LLC
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

using System;
using System.Buffers;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using size_t = nuint;

namespace Nethermind.Crypto;

public static partial class Bls
{
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial size_t blst_p1_affine_sizeof();

    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial ERROR blst_p1_deserialize(Span<long> ret, ReadOnlySpan<byte> inp);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_p1_affine_serialize(Span<byte> ret, ReadOnlySpan<long> inp);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_p1_affine_compress(Span<byte> ret, ReadOnlySpan<long> inp);

    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_p1_to_affine(Span<long> ret, ReadOnlySpan<long> inp);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool blst_p1_affine_on_curve(ReadOnlySpan<long> point);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool blst_p1_affine_in_g1(ReadOnlySpan<long> point);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool blst_p1_affine_is_inf(ReadOnlySpan<long> point);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool blst_p1_affine_is_equal(ReadOnlySpan<long> a, ReadOnlySpan<long> b);

    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial nint blst_p1_generator();

    public readonly ref struct P1Affine
    {
        public readonly ReadOnlySpan<long> Point { get => _point; }
        public static int Sz { get => _sz; }
        private readonly Span<long> _point;
        private static readonly int _sz = (int)blst_p1_affine_sizeof() / sizeof(long);

        public P1Affine(P1Affine p)
        {
            _point = new long[Sz];
            p._point.CopyTo(_point);
        }

        public P1Affine(Span<long> p)
        {
            if (p.Length < Sz)
            {
                throw new ArgumentException($"Invalid point length. Expected {_sz} longs.");
            }
            _point = p[..Sz];
        }

        public P1Affine()
        {
            _point = new long[Sz];
        }

        public P1Affine(scoped ReadOnlySpan<byte> inp) : this()
            => Decode(inp);

        public readonly void Zero()
            => _point.Clear();

        public bool TryDecode(scoped ReadOnlySpan<byte> inp, out ERROR err)
        {
            int len = inp.Length;
            if (len == 0 || len != ((inp[0] & 0x80) == 0x80 ? P1_COMPRESSED_SZ
                                                          : 2 * P1_COMPRESSED_SZ))
            {
                err = ERROR.BADENCODING;
                return false;
            }

            err = blst_p1_deserialize(_point, inp);
            if (err != ERROR.SUCCESS)
            {
                return false;
            }

            return true;
        }

        public void Decode(scoped ReadOnlySpan<byte> inp)
        {
            if (!TryDecode(inp, out ERROR err))
            {
                throw new BlsException(err);
            }
        }

        /// <summary>Decodes raw affine coordinates without any validation, as in <see cref="P1.Decode(ReadOnlySpan{byte}, ReadOnlySpan{byte})"/>.</summary>
        public void Decode(ReadOnlySpan<byte> fp1, ReadOnlySpan<byte> fp2)
        {
            if (fp1.Length != 48 || fp2.Length != 48)
            {
                throw new ArgumentException("Invalid input length. Expected 48 bytes for each field element.");
            }

            blst_fp_from_bendian(_point, fp1);
            blst_fp_from_bendian(_point[6..], fp2);
        }

        public P1Affine(P1 jacobian) : this()
            => blst_p1_to_affine(_point, jacobian.Point);

        public P1Affine Dup() => new(this);
        public P1 ToJacobian() => new(this);
        public byte[] Serialize()
        {
            byte[] ret = new byte[2 * P1_COMPRESSED_SZ];
            blst_p1_affine_serialize(ret, _point);
            return ret;
        }
        public byte[] Compress()
        {
            byte[] ret = new byte[P1_COMPRESSED_SZ];
            blst_p1_affine_compress(ret, _point);
            return ret;
        }

        public bool OnCurve()
            => blst_p1_affine_on_curve(_point);
        public bool InGroup()
            => blst_p1_affine_in_g1(_point);
        public bool IsInf()
            => blst_p1_affine_is_inf(_point);
        public bool IsEqual(P1Affine p)
            => blst_p1_affine_is_equal(_point, p._point);

        public static P1Affine Generator()
        {
            long[] res = new long[Sz];
            return Generator(res);
        }

        public static unsafe P1Affine Generator(Span<long> p)
        {
            P1Affine res = new(p);
            new ReadOnlySpan<long>((void*)blst_p1_generator(), Sz).CopyTo(res._point);
            return res;
        }
    }

    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial size_t blst_p1_sizeof();
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_p1_serialize(Span<byte> ret, ReadOnlySpan<long> inp);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_p1_compress(Span<byte> ret, ReadOnlySpan<long> inp);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_p1_from_affine(Span<long> ret, ReadOnlySpan<long> inp);

    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool blst_p1_on_curve(ReadOnlySpan<long> point);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool blst_p1_in_g1(ReadOnlySpan<long> point);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool blst_p1_is_inf(ReadOnlySpan<long> point);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static partial bool blst_p1_is_equal(ReadOnlySpan<long> a, ReadOnlySpan<long> b);

    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_sk_to_pk_in_g1(Span<long> ret, ReadOnlySpan<byte> SK);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_map_to_g1(Span<long> ret, ReadOnlySpan<long> u, ReadOnlySpan<long> v);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_encode_to_g1(Span<long> ret, ReadOnlySpan<byte> msg, size_t msg_len,
                                             ReadOnlySpan<byte> dst, size_t dst_len,
                                             ReadOnlySpan<byte> aug, size_t aug_len);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_hash_to_g1(Span<long> ret, ReadOnlySpan<byte> msg, size_t msg_len,
                                           ReadOnlySpan<byte> dst, size_t dst_len,
                                           ReadOnlySpan<byte> aug, size_t aug_len);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_sign_pk_in_g2(Span<long> ret, ReadOnlySpan<long> hash, ReadOnlySpan<byte> SK);

    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_p1_mult(Span<long> ret, ReadOnlySpan<long> a,
                                        ReadOnlySpan<byte> scalar, size_t nbits);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_p1_cneg(Span<long> ret, [MarshalAs(UnmanagedType.Bool)] bool cbit);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_p1_add_or_double(Span<long> ret, ReadOnlySpan<long> a, ReadOnlySpan<long> b);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_p1_add_or_double_affine(Span<long> ret, ReadOnlySpan<long> a,
                                                        ReadOnlySpan<long> b);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial void blst_p1_double(Span<long> ret, ReadOnlySpan<long> a);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static partial size_t blst_p1s_mult_pippenger_scratch_sizeof(size_t npoints);
    // void blst_p1s_mult_pippenger(blst_p1 *ret, const blst_p1_affine *const points[],
    //                          size_t npoints, const byte *const scalars[],
    //                          size_t nbits, limb_t *scratch);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static unsafe partial void blst_p1s_mult_pippenger(Span<long> ret, long** points,
        size_t npoints, byte** scalars, size_t nbits, long* scratch);

    // void blst_p1s_to_affine(blst_p1_affine dst[], const blst_p1 *const points[],
    //                     size_t npoints);
    [LibraryImport(LibraryName)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    private static unsafe partial void blst_p1s_to_affine(Span<long> dst, long** points, size_t npoints);

    public readonly ref struct P1
    {
        public readonly ReadOnlySpan<long> Point { get => _point; }
        public static int Sz { get => _sz; }
        private readonly Span<long> _point;
        private static readonly int _sz = (int)blst_p1_sizeof() / sizeof(long);

        public P1(P1 p)
        {
            _point = new long[Sz];
            p._point.CopyTo(_point);
        }

        public P1(Span<long> p)
        {
            if (p.Length < Sz)
            {
                throw new ArgumentException($"Invalid point length. Expected {_sz} longs.");
            }
            _point = p[..Sz];
        }

        public P1()
        {
            _point = new long[Sz];
        }

        public P1(SecretKey sk) : this()
            => FromSk(sk);

        public void FromSk(SecretKey sk)
        { blst_sk_to_pk_in_g1(_point, sk.Key); }

        public P1(scoped ReadOnlySpan<byte> inp) : this()
            => Decode(inp);

        public readonly void Zero()
            => _point.Clear();

        /// <summary>
        /// Decodes a 48-byte compressed or 96-byte uncompressed point.
        /// Unlike <see cref="P1Affine.TryDecode"/>, the uncompressed path reads the two field
        /// elements as-is with no validation (no canonicality, flag-bit, curve or subgroup checks),
        /// so that callers implementing protocols such as EIP-2537 can validate separately.
        /// Call <see cref="OnCurve"/>/<see cref="InGroup"/> where validation is required.
        /// </summary>
        public bool TryDecode(scoped ReadOnlySpan<byte> inp, out ERROR err)
        {
            int len = inp.Length;
            if (len == 0 || len != ((inp[0] & 0x80) == 0x80 ? P1_COMPRESSED_SZ
                                                          : 2 * P1_COMPRESSED_SZ))
            {
                err = ERROR.BADENCODING;
                return false;
            }

            if (len == 2 * P1_COMPRESSED_SZ)
            {
                blst_fp_from_bendian(_point, inp[..48]);
                blst_fp_from_bendian(_point[6..], inp[48..]);
            }
            else
            {
                err = blst_p1_deserialize(_point, inp);
                if (err != ERROR.SUCCESS)
                {
                    return false;
                }
            }

            blst_p1_from_affine(_point, _point);

            err = ERROR.SUCCESS;
            return true;
        }

        /// <summary>Decodes raw affine coordinates without any validation, as in <see cref="TryDecode"/>.</summary>
        public void Decode(ReadOnlySpan<byte> fp1, ReadOnlySpan<byte> fp2)
        {
            if (fp1.Length != 48 || fp2.Length != 48)
            {
                throw new ArgumentException("Invalid input length. Expected 48 bytes for each field element.");
            }

            blst_fp_from_bendian(_point, fp1);
            blst_fp_from_bendian(_point[6..], fp2);
            blst_p1_from_affine(_point, _point);
        }

        public void Decode(scoped ReadOnlySpan<byte> inp)
        {
            if (!TryDecode(inp, out ERROR err))
            {
                throw new BlsException(err);
            }
        }

        public P1(P1Affine affine) : this()
        { blst_p1_from_affine(_point, affine.Point); }

        public readonly P1 Dup() => new(this);
        public readonly P1Affine ToAffine() => new(this);
        public readonly byte[] Serialize()
        {
            byte[] ret = new byte[2 * P1_COMPRESSED_SZ];
            blst_p1_serialize(ret, _point);
            return ret;
        }
        public readonly byte[] Compress()
        {
            byte[] ret = new byte[P1_COMPRESSED_SZ];
            blst_p1_compress(ret, _point);
            return ret;
        }

        public readonly bool OnCurve()
            => blst_p1_on_curve(_point);
        public readonly bool InGroup()
            => blst_p1_in_g1(_point);
        public readonly bool IsInf()
            => blst_p1_is_inf(_point);
        public readonly bool IsEqual(P1 p)
            => blst_p1_is_equal(_point, p._point);

        public readonly P1 MapTo(scoped ReadOnlySpan<byte> fp)
        {
            if (fp.Length != 48)
            {
                throw new ArgumentException("Invalid input length. Expected 48 bytes.", nameof(fp));
            }

            Span<long> u = stackalloc long[6];
            blst_fp_from_bendian(u, fp);
            blst_map_to_g1(_point, u, default);
            return this;
        }
        public readonly P1 HashTo(scoped ReadOnlySpan<byte> msg, ReadOnlySpan<byte> DST = default, ReadOnlySpan<byte> aug = default)
        {
            blst_hash_to_g1(_point, msg, (size_t)msg.Length,
                                    DST, (size_t)DST.Length,
                                    aug, (size_t)(!aug.IsEmpty ? aug.Length : 0));
            return this;
        }
        public readonly P1 EncodeTo(scoped ReadOnlySpan<byte> msg, ReadOnlySpan<byte> DST = default, ReadOnlySpan<byte> aug = default)
        {
            blst_encode_to_g1(_point, msg, (size_t)msg.Length,
                                      DST, (size_t)DST.Length,
                                      aug, (size_t)(!aug.IsEmpty ? aug.Length : 0));
            return this;
        }

        public readonly P1 SignWith(SecretKey sk)
        { blst_sign_pk_in_g2(_point, _point, sk.Key); return this; }
        public readonly P1 SignWith(Scalar scalar)
        { blst_sign_pk_in_g2(_point, _point, scalar.Val); return this; }

        public readonly void Aggregate(P1Affine inp)
        {
            if (blst_p1_affine_in_g1(inp.Point))
            {
                blst_p1_add_or_double_affine(_point, _point, inp.Point);
            }
            else
            {
                throw new BlsException(ERROR.POINTNOTINGROUP);
            }
        }

        public readonly P1 Mult(scoped ReadOnlySpan<byte> scalar)
        {
            blst_p1_mult(_point, _point, scalar, (size_t)(scalar.Length * 8));
            return this;
        }
        public readonly P1 Mult(Scalar scalar)
        {
            blst_p1_mult(_point, _point, scalar.Val, 255);
            return this;
        }

        private readonly byte[] PrepareMult(in BigInteger scalar)
        {
            byte[] val;
            if (scalar.Sign < 0)
            {
                val = BigInteger.Negate(scalar).ToByteArray();
                blst_p1_cneg(_point, true);
            }
            else
            {
                val = scalar.ToByteArray();
            }
            return val;
        }
        private static size_t GetSize(ReadOnlySpan<byte> val)
        {
            int len = val.Length;
            if (val[len - 1] == 0) len--;
            return (size_t)len;
        }
        public readonly P1 Mult(in BigInteger scalar)
        {
            byte[] val = PrepareMult(scalar);
            size_t len = GetSize(val);
            blst_p1_mult(_point, _point, val, len * 8);
            return this;
        }

        /// <summary>
        /// Multi-scalar multiplication over <paramref name="npoints"/> Jacobian points stored
        /// contiguously in <paramref name="rawPoints"/> with 32-byte little-endian scalars stored
        /// contiguously in <paramref name="rawScalars"/>. Points at infinity must be filtered out
        /// by the caller.
        /// </summary>
        public readonly unsafe P1 MultiMult(scoped ReadOnlySpan<long> rawPoints, scoped ReadOnlySpan<byte> rawScalars, int npoints)
        {
            ArgumentOutOfRangeException.ThrowIfNegative(npoints);
            if (rawPoints.Length < npoints * Sz)
            {
                throw new ArgumentException($"Insufficient points for the given count. Expected {npoints * Sz} longs.", nameof(rawPoints));
            }
            if (rawScalars.Length < npoints * 32)
            {
                throw new ArgumentException($"Insufficient scalars for the given count. Expected {npoints * 32} bytes.", nameof(rawScalars));
            }

            // blst does not support an empty multiplication; the result is the point at infinity
            if (npoints == 0)
            {
                Zero();
                return this;
            }

            int affinesLen = npoints * P1Affine.Sz;
            long[] affines = ArrayPool<long>.Shared.Rent(affinesLen);

            try
            {
                // a [ptr, null] argument tells blst to read all points from one contiguous buffer
                fixed (long* rawPointsPtr = rawPoints)
                {
                    long** points = stackalloc long*[2] { rawPointsPtr, null };
                    blst_p1s_to_affine(affines.AsSpan(0, affinesLen), points, (size_t)npoints);
                }

                return MultiMultAffine(affines.AsSpan(0, affinesLen), rawScalars, npoints);
            }
            finally
            {
                ArrayPool<long>.Shared.Return(affines);
            }
        }

        /// <summary>
        /// As <see cref="MultiMult"/>, but over affine points, skipping the Jacobian-to-affine
        /// batch conversion.
        /// </summary>
        public readonly unsafe P1 MultiMultAffine(scoped ReadOnlySpan<long> rawAffines, scoped ReadOnlySpan<byte> rawScalars, int npoints)
        {
            ArgumentOutOfRangeException.ThrowIfNegative(npoints);
            if (rawAffines.Length < npoints * P1Affine.Sz)
            {
                throw new ArgumentException($"Insufficient points for the given count. Expected {npoints * P1Affine.Sz} longs.", nameof(rawAffines));
            }
            if (rawScalars.Length < npoints * 32)
            {
                throw new ArgumentException($"Insufficient scalars for the given count. Expected {npoints * 32} bytes.", nameof(rawScalars));
            }

            // blst does not support an empty multiplication; the result is the point at infinity
            if (npoints == 0)
            {
                Zero();
                return this;
            }

            int scratchLen = (int)(blst_p1s_mult_pippenger_scratch_sizeof((size_t)npoints) / sizeof(long));
            long[] scratch = ArrayPool<long>.Shared.Rent(scratchLen);

            try
            {
                fixed (long* affinesPtr = rawAffines)
                fixed (byte* scalarsPtr = rawScalars)
                fixed (long* scratchPtr = scratch)
                {
                    long** points = stackalloc long*[2] { affinesPtr, null };
                    byte** scalars = stackalloc byte*[2] { scalarsPtr, null };
                    blst_p1s_mult_pippenger(_point, points, (size_t)npoints, scalars, 256, scratchPtr);
                }
            }
            finally
            {
                ArrayPool<long>.Shared.Return(scratch);
            }

            return this;
        }
        public readonly P1 Cneg(bool flag) { blst_p1_cneg(_point, flag); return this; }
        public readonly P1 Neg() { blst_p1_cneg(_point, true); return this; }
        public readonly P1 Add(P1 a)
        { blst_p1_add_or_double(_point, _point, a._point); return this; }
        public readonly P1 Add(P1Affine a)
        { blst_p1_add_or_double_affine(_point, _point, a.Point); return this; }
        public readonly P1 Dbl()
        { blst_p1_double(_point, _point); return this; }

        public static P1 Generator()
        {
            long[] res = new long[Sz];
            return Generator(res);
        }

        public static unsafe P1 Generator(Span<long> p)
        {
            P1 res = new(p);
            new ReadOnlySpan<long>((void*)blst_p1_generator(), Sz).CopyTo(res._point);
            return res;
        }
    }

    public static P1 G1() => P1.Generator();
}
